; Auto-generated. Do not edit!


(cl:in-package ld_actions-msg)


;//! \htmlinclude PatrolResumeGoal.msg.html

(cl:defclass <PatrolResumeGoal> (roslisp-msg-protocol:ros-message)
  ((goal_patrol
    :reader goal_patrol
    :initarg :goal_patrol
    :type cl:string
    :initform ""))
)

(cl:defclass PatrolResumeGoal (<PatrolResumeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolResumeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolResumeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ld_actions-msg:<PatrolResumeGoal> is deprecated: use ld_actions-msg:PatrolResumeGoal instead.")))

(cl:ensure-generic-function 'goal_patrol-val :lambda-list '(m))
(cl:defmethod goal_patrol-val ((m <PatrolResumeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ld_actions-msg:goal_patrol-val is deprecated.  Use ld_actions-msg:goal_patrol instead.")
  (goal_patrol m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolResumeGoal>) ostream)
  "Serializes a message object of type '<PatrolResumeGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_patrol))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_patrol))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolResumeGoal>) istream)
  "Deserializes a message object of type '<PatrolResumeGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_patrol) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_patrol) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolResumeGoal>)))
  "Returns string type for a message object of type '<PatrolResumeGoal>"
  "ld_actions/PatrolResumeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolResumeGoal)))
  "Returns string type for a message object of type 'PatrolResumeGoal"
  "ld_actions/PatrolResumeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolResumeGoal>)))
  "Returns md5sum for a message object of type '<PatrolResumeGoal>"
  "bbc29a4d7d524ef00ce6e69ba1c4a816")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolResumeGoal)))
  "Returns md5sum for a message object of type 'PatrolResumeGoal"
  "bbc29a4d7d524ef00ce6e69ba1c4a816")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolResumeGoal>)))
  "Returns full string definition for message of type '<PatrolResumeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_patrol~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolResumeGoal)))
  "Returns full string definition for message of type 'PatrolResumeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_patrol~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolResumeGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_patrol))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolResumeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolResumeGoal
    (cl:cons ':goal_patrol (goal_patrol msg))
))
