; Auto-generated. Do not edit!


(cl:in-package ld_actions-msg)


;//! \htmlinclude StopGoal.msg.html

(cl:defclass <StopGoal> (roslisp-msg-protocol:ros-message)
  ((goal_stop
    :reader goal_stop
    :initarg :goal_stop
    :type cl:string
    :initform ""))
)

(cl:defclass StopGoal (<StopGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ld_actions-msg:<StopGoal> is deprecated: use ld_actions-msg:StopGoal instead.")))

(cl:ensure-generic-function 'goal_stop-val :lambda-list '(m))
(cl:defmethod goal_stop-val ((m <StopGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ld_actions-msg:goal_stop-val is deprecated.  Use ld_actions-msg:goal_stop instead.")
  (goal_stop m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopGoal>) ostream)
  "Serializes a message object of type '<StopGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_stop))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_stop))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopGoal>) istream)
  "Deserializes a message object of type '<StopGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_stop) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_stop) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopGoal>)))
  "Returns string type for a message object of type '<StopGoal>"
  "ld_actions/StopGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopGoal)))
  "Returns string type for a message object of type 'StopGoal"
  "ld_actions/StopGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopGoal>)))
  "Returns md5sum for a message object of type '<StopGoal>"
  "cb7b95c39be20820c1c7a2575bd9c5d5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopGoal)))
  "Returns md5sum for a message object of type 'StopGoal"
  "cb7b95c39be20820c1c7a2575bd9c5d5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopGoal>)))
  "Returns full string definition for message of type '<StopGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_stop~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopGoal)))
  "Returns full string definition for message of type 'StopGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_stop~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_stop))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StopGoal
    (cl:cons ':goal_stop (goal_stop msg))
))
