// Generated by gencpp from file om_aiv_navigation/DockGoal.msg
// DO NOT EDIT!


#ifndef OM_AIV_NAVIGATION_MESSAGE_DOCKGOAL_H
#define OM_AIV_NAVIGATION_MESSAGE_DOCKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace om_aiv_navigation
{
template <class ContainerAllocator>
struct DockGoal_
{
  typedef DockGoal_<ContainerAllocator> Type;

  DockGoal_()
    : goal_dock()  {
    }
  DockGoal_(const ContainerAllocator& _alloc)
    : goal_dock(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_dock_type;
  _goal_dock_type goal_dock;





  typedef boost::shared_ptr< ::om_aiv_navigation::DockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::om_aiv_navigation::DockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DockGoal_

typedef ::om_aiv_navigation::DockGoal_<std::allocator<void> > DockGoal;

typedef boost::shared_ptr< ::om_aiv_navigation::DockGoal > DockGoalPtr;
typedef boost::shared_ptr< ::om_aiv_navigation::DockGoal const> DockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::om_aiv_navigation::DockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace om_aiv_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'om_aiv_navigation': ['/home/tthmatt/Omron_LD_ROS_Package/devel/.private/om_aiv_navigation/share/om_aiv_navigation/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::om_aiv_navigation::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om_aiv_navigation::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om_aiv_navigation::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f27dd24d1ef775e8d5a9739d7a2dc59";
  }

  static const char* value(const ::om_aiv_navigation::DockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f27dd24d1ef775eULL;
  static const uint64_t static_value2 = 0x8d5a9739d7a2dc59ULL;
};

template<class ContainerAllocator>
struct DataType< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "om_aiv_navigation/DockGoal";
  }

  static const char* value(const ::om_aiv_navigation::DockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string goal_dock\n"
"\n"
;
  }

  static const char* value(const ::om_aiv_navigation::DockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_dock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::om_aiv_navigation::DockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::om_aiv_navigation::DockGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_dock: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_dock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OM_AIV_NAVIGATION_MESSAGE_DOCKGOAL_H
