= LD-ROS - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title: Table of Contents
:toc-placement: preamble
:icons: font
:sectnums:
:imagesDir: images
:librariesDir: ../libraries
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
:linkattrs:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

:url-repo: https://github.com/zach-goh/OmronRepos/tree/master
:url-ug: https://github.com/zach-goh/OmronRepos/blob/master/docs/UserGuide.adoc

Last updated: `9 JULY 2020` By: `Xavier`

== Authors

* Xavier, Lee Kok Teng (link:https://github.com/lekoook[lekoook])

== Getting Started
[[prerequisites]]
=== Prerequisites

. **Git**
+
* Download link:https://git-scm.com/downloads[Git]. 
+
* If you are a beginner to `Git` version-control system, you are suggested to download GUI clients to assist you. Some examples can be found link:https://git-scm.com/downloads/guis/[here].
+
* There are many resources to learn how to use `Git`, see link:https://git-scm.com/doc[here], link:https://try.github.io/[here], link:https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners[here]. Google for more.

. **Ubuntu 18.04 LTS (Bionic Beaver)**
+
See link:https://ubuntu.com/[Ubuntu] webpage for installation instructions. Look for 18.04 release.
+
Although ROS is officially supported on multiple platforms include Windows OS (experimental), Ubuntu OS is preferred since support for packages on Ubuntu platform is more matured. Additionally, this package is tested to be working on Ubuntu platform.

. **Robot Operating System (ROS) Melodic Release**
+
Download and installation instructions can be found link:http://wiki.ros.org/melodic/Installation[here].
+
__LD-ROS__ is currently supported on ROS 1 Melodic only.
+

. **How to use ROS**
+
This guide assumes you know the basics of using the ROS environment. If you are new to ROS, please follow their series of link:http://wiki.ros.org/ROS/Tutorials[tutorials] to get started with using ROS.
+
You will need to complete the `Beginner Level` tutorials at the minimum. As well as `Running ROS across multiple machines` and `Defining Custom Messages` in the `Intermediate Level` tutorials.

. **'selector2' Python2 module**
+
__LD-ROS__ uses Python low-level socket to communicate with the LD robot. __selector2__ is used to assist in managing the reading/writing process through these sockets.
+
See link:https://pypi.org/project/selectors2/[selectors2].

. **Telnet**
+
Telnet application. This is only used for directly communicating with LD's ARCL interface via a command line interface.

=== Prepare Project
The instructions here assumes you have basic knowledge of using Git, Ubuntu, Bash terminal and ROS environment.

Follow these steps to run this package:

. Make sure you have met the requirements in <<prerequisites>>.
. Clone this repository to a directory of your choice with `git clone`.
. Supposed you have cloned this to your home directory, go there with `cd ~/Omron_LD_ROS_Package`.
. Build this package with `catkin build`. Depending on your machine, this can a while to build.
. After it has built successfully, ensure you source this workspace with `source ~/Omron_LD_ROS_Package/devel/setup.bash`
. Run the 