// Generated by gencpp from file om_aiv_util/OmAivService.msg
// DO NOT EDIT!


#ifndef OM_AIV_UTIL_MESSAGE_OMAIVSERVICE_H
#define OM_AIV_UTIL_MESSAGE_OMAIVSERVICE_H

#include <ros/service_traits.h>


#include <om_aiv_util/OmAivServiceRequest.h>
#include <om_aiv_util/OmAivServiceResponse.h>


namespace om_aiv_util
{

struct OmAivService
{

typedef OmAivServiceRequest Request;
typedef OmAivServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OmAivService
} // namespace om_aiv_util


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::om_aiv_util::OmAivService > {
  static const char* value()
  {
    return "b2778cec932742b2c8b6d125219e8d85";
  }

  static const char* value(const ::om_aiv_util::OmAivService&) { return value(); }
};

template<>
struct DataType< ::om_aiv_util::OmAivService > {
  static const char* value()
  {
    return "om_aiv_util/OmAivService";
  }

  static const char* value(const ::om_aiv_util::OmAivService&) { return value(); }
};


// service_traits::MD5Sum< ::om_aiv_util::OmAivServiceRequest> should match 
// service_traits::MD5Sum< ::om_aiv_util::OmAivService > 
template<>
struct MD5Sum< ::om_aiv_util::OmAivServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::OmAivService >::value();
  }
  static const char* value(const ::om_aiv_util::OmAivServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::OmAivServiceRequest> should match 
// service_traits::DataType< ::om_aiv_util::OmAivService > 
template<>
struct DataType< ::om_aiv_util::OmAivServiceRequest>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::OmAivService >::value();
  }
  static const char* value(const ::om_aiv_util::OmAivServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::om_aiv_util::OmAivServiceResponse> should match 
// service_traits::MD5Sum< ::om_aiv_util::OmAivService > 
template<>
struct MD5Sum< ::om_aiv_util::OmAivServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::OmAivService >::value();
  }
  static const char* value(const ::om_aiv_util::OmAivServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::OmAivServiceResponse> should match 
// service_traits::DataType< ::om_aiv_util::OmAivService > 
template<>
struct DataType< ::om_aiv_util::OmAivServiceResponse>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::OmAivService >::value();
  }
  static const char* value(const ::om_aiv_util::OmAivServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OM_AIV_UTIL_MESSAGE_OMAIVSERVICE_H
