// Generated by gencpp from file om_aiv_util/Service3.msg
// DO NOT EDIT!


#ifndef OM_AIV_UTIL_MESSAGE_SERVICE3_H
#define OM_AIV_UTIL_MESSAGE_SERVICE3_H

#include <ros/service_traits.h>


#include <om_aiv_util/Service3Request.h>
#include <om_aiv_util/Service3Response.h>


namespace om_aiv_util
{

struct Service3
{

typedef Service3Request Request;
typedef Service3Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service3
} // namespace om_aiv_util


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::om_aiv_util::Service3 > {
  static const char* value()
  {
    return "6d29793b95b92fdf3218d77308234efd";
  }

  static const char* value(const ::om_aiv_util::Service3&) { return value(); }
};

template<>
struct DataType< ::om_aiv_util::Service3 > {
  static const char* value()
  {
    return "om_aiv_util/Service3";
  }

  static const char* value(const ::om_aiv_util::Service3&) { return value(); }
};


// service_traits::MD5Sum< ::om_aiv_util::Service3Request> should match 
// service_traits::MD5Sum< ::om_aiv_util::Service3 > 
template<>
struct MD5Sum< ::om_aiv_util::Service3Request>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::Service3 >::value();
  }
  static const char* value(const ::om_aiv_util::Service3Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::Service3Request> should match 
// service_traits::DataType< ::om_aiv_util::Service3 > 
template<>
struct DataType< ::om_aiv_util::Service3Request>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::Service3 >::value();
  }
  static const char* value(const ::om_aiv_util::Service3Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::om_aiv_util::Service3Response> should match 
// service_traits::MD5Sum< ::om_aiv_util::Service3 > 
template<>
struct MD5Sum< ::om_aiv_util::Service3Response>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::Service3 >::value();
  }
  static const char* value(const ::om_aiv_util::Service3Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::Service3Response> should match 
// service_traits::DataType< ::om_aiv_util::Service3 > 
template<>
struct DataType< ::om_aiv_util::Service3Response>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::Service3 >::value();
  }
  static const char* value(const ::om_aiv_util::Service3Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OM_AIV_UTIL_MESSAGE_SERVICE3_H
