// Generated by gencpp from file om_aiv_util/ServiceExample.msg
// DO NOT EDIT!


#ifndef OM_AIV_UTIL_MESSAGE_SERVICEEXAMPLE_H
#define OM_AIV_UTIL_MESSAGE_SERVICEEXAMPLE_H

#include <ros/service_traits.h>


#include <om_aiv_util/ServiceExampleRequest.h>
#include <om_aiv_util/ServiceExampleResponse.h>


namespace om_aiv_util
{

struct ServiceExample
{

typedef ServiceExampleRequest Request;
typedef ServiceExampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceExample
} // namespace om_aiv_util


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::om_aiv_util::ServiceExample > {
  static const char* value()
  {
    return "b6541b31be965d2ea76445e10907a742";
  }

  static const char* value(const ::om_aiv_util::ServiceExample&) { return value(); }
};

template<>
struct DataType< ::om_aiv_util::ServiceExample > {
  static const char* value()
  {
    return "om_aiv_util/ServiceExample";
  }

  static const char* value(const ::om_aiv_util::ServiceExample&) { return value(); }
};


// service_traits::MD5Sum< ::om_aiv_util::ServiceExampleRequest> should match 
// service_traits::MD5Sum< ::om_aiv_util::ServiceExample > 
template<>
struct MD5Sum< ::om_aiv_util::ServiceExampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::ServiceExample >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::ServiceExampleRequest> should match 
// service_traits::DataType< ::om_aiv_util::ServiceExample > 
template<>
struct DataType< ::om_aiv_util::ServiceExampleRequest>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::ServiceExample >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::om_aiv_util::ServiceExampleResponse> should match 
// service_traits::MD5Sum< ::om_aiv_util::ServiceExample > 
template<>
struct MD5Sum< ::om_aiv_util::ServiceExampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::ServiceExample >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceExampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::ServiceExampleResponse> should match 
// service_traits::DataType< ::om_aiv_util::ServiceExample > 
template<>
struct DataType< ::om_aiv_util::ServiceExampleResponse>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::ServiceExample >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceExampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OM_AIV_UTIL_MESSAGE_SERVICEEXAMPLE_H
