// Generated by gencpp from file om_aiv_util/Service.msg
// DO NOT EDIT!


#ifndef OM_AIV_UTIL_MESSAGE_SERVICE_H
#define OM_AIV_UTIL_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <om_aiv_util/ServiceRequest.h>
#include <om_aiv_util/ServiceResponse.h>


namespace om_aiv_util
{

struct Service
{

typedef ServiceRequest Request;
typedef ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service
} // namespace om_aiv_util


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::om_aiv_util::Service > {
  static const char* value()
  {
    return "04de0574add1d5e8526e6869cdd49c0c";
  }

  static const char* value(const ::om_aiv_util::Service&) { return value(); }
};

template<>
struct DataType< ::om_aiv_util::Service > {
  static const char* value()
  {
    return "om_aiv_util/Service";
  }

  static const char* value(const ::om_aiv_util::Service&) { return value(); }
};


// service_traits::MD5Sum< ::om_aiv_util::ServiceRequest> should match 
// service_traits::MD5Sum< ::om_aiv_util::Service > 
template<>
struct MD5Sum< ::om_aiv_util::ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::Service >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::ServiceRequest> should match 
// service_traits::DataType< ::om_aiv_util::Service > 
template<>
struct DataType< ::om_aiv_util::ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::Service >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::om_aiv_util::ServiceResponse> should match 
// service_traits::MD5Sum< ::om_aiv_util::Service > 
template<>
struct MD5Sum< ::om_aiv_util::ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::om_aiv_util::Service >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::om_aiv_util::ServiceResponse> should match 
// service_traits::DataType< ::om_aiv_util::Service > 
template<>
struct DataType< ::om_aiv_util::ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::om_aiv_util::Service >::value();
  }
  static const char* value(const ::om_aiv_util::ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OM_AIV_UTIL_MESSAGE_SERVICE_H
