// Auto-generated. Do not edit!

// (in-package ld_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoTaskGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goaltask = null;
    }
    else {
      if (initObj.hasOwnProperty('goaltask')) {
        this.goaltask = initObj.goaltask
      }
      else {
        this.goaltask = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoTaskGoal
    // Serialize message field [goaltask]
    bufferOffset = _serializer.string(obj.goaltask, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoTaskGoal
    let len;
    let data = new DoTaskGoal(null);
    // Deserialize message field [goaltask]
    data.goaltask = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.goaltask.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ld_actions/DoTaskGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3d5cc085a1398fe4922199f479159c57';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string goaltask
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoTaskGoal(null);
    if (msg.goaltask !== undefined) {
      resolved.goaltask = msg.goaltask;
    }
    else {
      resolved.goaltask = ''
    }

    return resolved;
    }
};

module.exports = DoTaskGoal;
