; Auto-generated. Do not edit!


(cl:in-package actions_tutorial-msg)


;//! \htmlinclude DockResult.msg.html

(cl:defclass <DockResult> (roslisp-msg-protocol:ros-message)
  ((docking_status
    :reader docking_status
    :initarg :docking_status
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass DockResult (<DockResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actions_tutorial-msg:<DockResult> is deprecated: use actions_tutorial-msg:DockResult instead.")))

(cl:ensure-generic-function 'docking_status-val :lambda-list '(m))
(cl:defmethod docking_status-val ((m <DockResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actions_tutorial-msg:docking_status-val is deprecated.  Use actions_tutorial-msg:docking_status instead.")
  (docking_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockResult>) ostream)
  "Serializes a message object of type '<DockResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'docking_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'docking_status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockResult>) istream)
  "Deserializes a message object of type '<DockResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'docking_status) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'docking_status)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockResult>)))
  "Returns string type for a message object of type '<DockResult>"
  "actions_tutorial/DockResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockResult)))
  "Returns string type for a message object of type 'DockResult"
  "actions_tutorial/DockResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockResult>)))
  "Returns md5sum for a message object of type '<DockResult>"
  "a47488ee9e6264003cfa058af9eb8e93")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockResult)))
  "Returns md5sum for a message object of type 'DockResult"
  "a47488ee9e6264003cfa058af9eb8e93")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockResult>)))
  "Returns full string definition for message of type '<DockResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string[] docking_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockResult)))
  "Returns full string definition for message of type 'DockResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string[] docking_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'docking_status) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DockResult
    (cl:cons ':docking_status (docking_status msg))
))
