; Auto-generated. Do not edit!


(cl:in-package actions_tutorial-msg)


;//! \htmlinclude WashTheDishesFeedback.msg.html

(cl:defclass <WashTheDishesFeedback> (roslisp-msg-protocol:ros-message)
  ((last_dish_washed
    :reader last_dish_washed
    :initarg :last_dish_washed
    :type cl:string
    :initform ""))
)

(cl:defclass WashTheDishesFeedback (<WashTheDishesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WashTheDishesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WashTheDishesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actions_tutorial-msg:<WashTheDishesFeedback> is deprecated: use actions_tutorial-msg:WashTheDishesFeedback instead.")))

(cl:ensure-generic-function 'last_dish_washed-val :lambda-list '(m))
(cl:defmethod last_dish_washed-val ((m <WashTheDishesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actions_tutorial-msg:last_dish_washed-val is deprecated.  Use actions_tutorial-msg:last_dish_washed instead.")
  (last_dish_washed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WashTheDishesFeedback>) ostream)
  "Serializes a message object of type '<WashTheDishesFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'last_dish_washed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'last_dish_washed))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WashTheDishesFeedback>) istream)
  "Deserializes a message object of type '<WashTheDishesFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'last_dish_washed) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'last_dish_washed) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WashTheDishesFeedback>)))
  "Returns string type for a message object of type '<WashTheDishesFeedback>"
  "actions_tutorial/WashTheDishesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WashTheDishesFeedback)))
  "Returns string type for a message object of type 'WashTheDishesFeedback"
  "actions_tutorial/WashTheDishesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WashTheDishesFeedback>)))
  "Returns md5sum for a message object of type '<WashTheDishesFeedback>"
  "cff4a52ffc57c5353f3b2128c70feaa7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WashTheDishesFeedback)))
  "Returns md5sum for a message object of type 'WashTheDishesFeedback"
  "cff4a52ffc57c5353f3b2128c70feaa7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WashTheDishesFeedback>)))
  "Returns full string definition for message of type '<WashTheDishesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string last_dish_washed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WashTheDishesFeedback)))
  "Returns full string definition for message of type 'WashTheDishesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string last_dish_washed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WashTheDishesFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'last_dish_washed))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WashTheDishesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'WashTheDishesFeedback
    (cl:cons ':last_dish_washed (last_dish_washed msg))
))
