// Generated by gencpp from file actions_tutorial/dockFeedback.msg
// DO NOT EDIT!


#ifndef ACTIONS_TUTORIAL_MESSAGE_DOCKFEEDBACK_H
#define ACTIONS_TUTORIAL_MESSAGE_DOCKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actions_tutorial
{
template <class ContainerAllocator>
struct dockFeedback_
{
  typedef dockFeedback_<ContainerAllocator> Type;

  dockFeedback_()
    : last_dish_washed()  {
    }
  dockFeedback_(const ContainerAllocator& _alloc)
    : last_dish_washed(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_dish_washed_type;
  _last_dish_washed_type last_dish_washed;





  typedef boost::shared_ptr< ::actions_tutorial::dockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actions_tutorial::dockFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct dockFeedback_

typedef ::actions_tutorial::dockFeedback_<std::allocator<void> > dockFeedback;

typedef boost::shared_ptr< ::actions_tutorial::dockFeedback > dockFeedbackPtr;
typedef boost::shared_ptr< ::actions_tutorial::dockFeedback const> dockFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actions_tutorial::dockFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actions_tutorial::dockFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actions_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actions_tutorial': ['/home/tthmatt/ld_ROS/devel/.private/actions_tutorial/share/actions_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::dockFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::dockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::dockFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cff4a52ffc57c5353f3b2128c70feaa7";
  }

  static const char* value(const ::actions_tutorial::dockFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcff4a52ffc57c535ULL;
  static const uint64_t static_value2 = 0x3f3b2128c70feaa7ULL;
};

template<class ContainerAllocator>
struct DataType< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actions_tutorial/dockFeedback";
  }

  static const char* value(const ::actions_tutorial::dockFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"string last_dish_washed\n"
"\n"
;
  }

  static const char* value(const ::actions_tutorial::dockFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last_dish_washed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dockFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actions_tutorial::dockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actions_tutorial::dockFeedback_<ContainerAllocator>& v)
  {
    s << indent << "last_dish_washed: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_dish_washed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONS_TUTORIAL_MESSAGE_DOCKFEEDBACK_H
