// Generated by gencpp from file actions_tutorial/DockGoal.msg
// DO NOT EDIT!


#ifndef ACTIONS_TUTORIAL_MESSAGE_DOCKGOAL_H
#define ACTIONS_TUTORIAL_MESSAGE_DOCKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actions_tutorial
{
template <class ContainerAllocator>
struct DockGoal_
{
  typedef DockGoal_<ContainerAllocator> Type;

  DockGoal_()
    : isdocked(0)  {
    }
  DockGoal_(const ContainerAllocator& _alloc)
    : isdocked(0)  {
  (void)_alloc;
    }



   typedef int32_t _isdocked_type;
  _isdocked_type isdocked;





  typedef boost::shared_ptr< ::actions_tutorial::DockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actions_tutorial::DockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DockGoal_

typedef ::actions_tutorial::DockGoal_<std::allocator<void> > DockGoal;

typedef boost::shared_ptr< ::actions_tutorial::DockGoal > DockGoalPtr;
typedef boost::shared_ptr< ::actions_tutorial::DockGoal const> DockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actions_tutorial::DockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actions_tutorial::DockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actions_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actions_tutorial': ['/home/tthmatt/ld_ROS/devel/.private/actions_tutorial/share/actions_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actions_tutorial::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2a74e0e3231023d3b4fd74b241fc57d";
  }

  static const char* value(const ::actions_tutorial::DockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2a74e0e3231023dULL;
  static const uint64_t static_value2 = 0x3b4fd74b241fc57dULL;
};

template<class ContainerAllocator>
struct DataType< ::actions_tutorial::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actions_tutorial/DockGoal";
  }

  static const char* value(const ::actions_tutorial::DockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actions_tutorial::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 isdocked\n"
"\n"
;
  }

  static const char* value(const ::actions_tutorial::DockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actions_tutorial::DockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isdocked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actions_tutorial::DockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actions_tutorial::DockGoal_<ContainerAllocator>& v)
  {
    s << indent << "isdocked: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isdocked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONS_TUTORIAL_MESSAGE_DOCKGOAL_H
