// Generated by gencpp from file actions_tutorial/WashTheDishesAction.msg
// DO NOT EDIT!


#ifndef ACTIONS_TUTORIAL_MESSAGE_WASHTHEDISHESACTION_H
#define ACTIONS_TUTORIAL_MESSAGE_WASHTHEDISHESACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <actions_tutorial/WashTheDishesActionGoal.h>
#include <actions_tutorial/WashTheDishesActionResult.h>
#include <actions_tutorial/WashTheDishesActionFeedback.h>

namespace actions_tutorial
{
template <class ContainerAllocator>
struct WashTheDishesAction_
{
  typedef WashTheDishesAction_<ContainerAllocator> Type;

  WashTheDishesAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  WashTheDishesAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::actions_tutorial::WashTheDishesActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::actions_tutorial::WashTheDishesActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::actions_tutorial::WashTheDishesActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> const> ConstPtr;

}; // struct WashTheDishesAction_

typedef ::actions_tutorial::WashTheDishesAction_<std::allocator<void> > WashTheDishesAction;

typedef boost::shared_ptr< ::actions_tutorial::WashTheDishesAction > WashTheDishesActionPtr;
typedef boost::shared_ptr< ::actions_tutorial::WashTheDishesAction const> WashTheDishesActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actions_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actions_tutorial': ['/home/tthmatt/ld_ROS/devel/.private/actions_tutorial/share/actions_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84036f4cba0114de90f6c6421733ab0a";
  }

  static const char* value(const ::actions_tutorial::WashTheDishesAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84036f4cba0114deULL;
  static const uint64_t static_value2 = 0x90f6c6421733ab0aULL;
};

template<class ContainerAllocator>
struct DataType< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actions_tutorial/WashTheDishesAction";
  }

  static const char* value(const ::actions_tutorial::WashTheDishesAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"WashTheDishesActionGoal action_goal\n"
"WashTheDishesActionResult action_result\n"
"WashTheDishesActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"WashTheDishesGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 number_of_minutes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"WashTheDishesResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"string[] dishes_washed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"WashTheDishesFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: actions_tutorial/WashTheDishesFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"string last_dish_washed\n"
"\n"
;
  }

  static const char* value(const ::actions_tutorial::WashTheDishesAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WashTheDishesAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actions_tutorial::WashTheDishesAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actions_tutorial::WashTheDishesAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::actions_tutorial::WashTheDishesActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::actions_tutorial::WashTheDishesActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::actions_tutorial::WashTheDishesActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONS_TUTORIAL_MESSAGE_WASHTHEDISHESACTION_H
