// Generated by gencpp from file ld_services/ServiceExampleResponse.msg
// DO NOT EDIT!


#ifndef LD_SERVICES_MESSAGE_SERVICEEXAMPLERESPONSE_H
#define LD_SERVICES_MESSAGE_SERVICEEXAMPLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ld_services
{
template <class ContainerAllocator>
struct ServiceExampleResponse_
{
  typedef ServiceExampleResponse_<ContainerAllocator> Type;

  ServiceExampleResponse_()
    : turn()  {
    }
  ServiceExampleResponse_(const ContainerAllocator& _alloc)
    : turn(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::ld_services::ServiceExampleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ld_services::ServiceExampleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceExampleResponse_

typedef ::ld_services::ServiceExampleResponse_<std::allocator<void> > ServiceExampleResponse;

typedef boost::shared_ptr< ::ld_services::ServiceExampleResponse > ServiceExampleResponsePtr;
typedef boost::shared_ptr< ::ld_services::ServiceExampleResponse const> ServiceExampleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ld_services::ServiceExampleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ld_services

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ld_services::ServiceExampleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_services::ServiceExampleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_services::ServiceExampleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "318653ac5e682e6ac5a91ab3fcbcfd51";
  }

  static const char* value(const ::ld_services::ServiceExampleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x318653ac5e682e6aULL;
  static const uint64_t static_value2 = 0xc5a91ab3fcbcfd51ULL;
};

template<class ContainerAllocator>
struct DataType< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ld_services/ServiceExampleResponse";
  }

  static const char* value(const ::ld_services::ServiceExampleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string turn\n"
"\n"
;
  }

  static const char* value(const ::ld_services::ServiceExampleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceExampleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ld_services::ServiceExampleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ld_services::ServiceExampleResponse_<ContainerAllocator>& v)
  {
    s << indent << "turn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LD_SERVICES_MESSAGE_SERVICEEXAMPLERESPONSE_H
