// Generated by gencpp from file ld_actions/DockGoal.msg
// DO NOT EDIT!


#ifndef LD_ACTIONS_MESSAGE_DOCKGOAL_H
#define LD_ACTIONS_MESSAGE_DOCKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ld_actions
{
template <class ContainerAllocator>
struct DockGoal_
{
  typedef DockGoal_<ContainerAllocator> Type;

  DockGoal_()
    : dock_goal(0)  {
    }
  DockGoal_(const ContainerAllocator& _alloc)
    : dock_goal(0)  {
  (void)_alloc;
    }



   typedef int32_t _dock_goal_type;
  _dock_goal_type dock_goal;





  typedef boost::shared_ptr< ::ld_actions::DockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ld_actions::DockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DockGoal_

typedef ::ld_actions::DockGoal_<std::allocator<void> > DockGoal;

typedef boost::shared_ptr< ::ld_actions::DockGoal > DockGoalPtr;
typedef boost::shared_ptr< ::ld_actions::DockGoal const> DockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ld_actions::DockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ld_actions::DockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ld_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ld_actions': ['/home/tthmatt/ld_ROS/devel/.private/ld_actions/share/ld_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ld_actions::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ld_actions::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_actions::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_actions::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_actions::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_actions::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ld_actions::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a83954aa55344db3d8b4a42866ccc3f";
  }

  static const char* value(const ::ld_actions::DockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a83954aa55344dbULL;
  static const uint64_t static_value2 = 0x3d8b4a42866ccc3fULL;
};

template<class ContainerAllocator>
struct DataType< ::ld_actions::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ld_actions/DockGoal";
  }

  static const char* value(const ::ld_actions::DockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ld_actions::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 dock_goal\n"
"\n"
;
  }

  static const char* value(const ::ld_actions::DockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ld_actions::DockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dock_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ld_actions::DockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ld_actions::DockGoal_<ContainerAllocator>& v)
  {
    s << indent << "dock_goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dock_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LD_ACTIONS_MESSAGE_DOCKGOAL_H
