// Generated by gencpp from file ld_actions/ExecuteMacroGoal.msg
// DO NOT EDIT!


#ifndef LD_ACTIONS_MESSAGE_EXECUTEMACROGOAL_H
#define LD_ACTIONS_MESSAGE_EXECUTEMACROGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ld_actions
{
template <class ContainerAllocator>
struct ExecuteMacroGoal_
{
  typedef ExecuteMacroGoal_<ContainerAllocator> Type;

  ExecuteMacroGoal_()
    : goal_macro()  {
    }
  ExecuteMacroGoal_(const ContainerAllocator& _alloc)
    : goal_macro(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_macro_type;
  _goal_macro_type goal_macro;





  typedef boost::shared_ptr< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMacroGoal_

typedef ::ld_actions::ExecuteMacroGoal_<std::allocator<void> > ExecuteMacroGoal;

typedef boost::shared_ptr< ::ld_actions::ExecuteMacroGoal > ExecuteMacroGoalPtr;
typedef boost::shared_ptr< ::ld_actions::ExecuteMacroGoal const> ExecuteMacroGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ld_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ld_actions': ['/home/tthmatt/ld_ROS/devel/.private/ld_actions/share/ld_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "548abab86be3e14a1a1ad893ef5685a5";
  }

  static const char* value(const ::ld_actions::ExecuteMacroGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x548abab86be3e14aULL;
  static const uint64_t static_value2 = 0x1a1ad893ef5685a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ld_actions/ExecuteMacroGoal";
  }

  static const char* value(const ::ld_actions::ExecuteMacroGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string goal_macro\n"
"\n"
;
  }

  static const char* value(const ::ld_actions::ExecuteMacroGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_macro);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteMacroGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ld_actions::ExecuteMacroGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ld_actions::ExecuteMacroGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_macro: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_macro);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LD_ACTIONS_MESSAGE_EXECUTEMACROGOAL_H
