(cl:defpackage om_aiv_util-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SERVICEEXAMPLE"
   "<SERVICEEXAMPLE-REQUEST>"
   "SERVICEEXAMPLE-REQUEST"
   "<SERVICEEXAMPLE-RESPONSE>"
   "SERVICEEXAMPLE-RESPONSE"
  ))

