(cl:defpackage om_aiv_util-srv
  (:use )
  (:export
   "SERVICE"
   "<SERVICE-REQUEST>"
   "SERVICE-REQUEST"
   "<SERVICE-RESPONSE>"
   "SERVICE-RESPONSE"
   "SERVICE5"
   "<SERVICE5-REQUEST>"
   "SERVICE5-REQUEST"
   "<SERVICE5-RESPONSE>"
   "SERVICE5-RESPONSE"
   "SERVICEEXAMPLE"
   "<SERVICEEXAMPLE-REQUEST>"
   "SERVICEEXAMPLE-REQUEST"
   "<SERVICEEXAMPLE-RESPONSE>"
   "SERVICEEXAMPLE-RESPONSE"
  ))

