// Auto-generated. Do not edit!

// (in-package actions_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.docking_status = null;
    }
    else {
      if (initObj.hasOwnProperty('docking_status')) {
        this.docking_status = initObj.docking_status
      }
      else {
        this.docking_status = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockResult
    // Serialize message field [docking_status]
    bufferOffset = _arraySerializer.string(obj.docking_status, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockResult
    let len;
    let data = new DockResult(null);
    // Deserialize message field [docking_status]
    data.docking_status = _arrayDeserializer.string(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.docking_status.forEach((val) => {
      length += 4 + val.length;
    });
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actions_tutorial/DockResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a47488ee9e6264003cfa058af9eb8e93';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    string[] docking_status
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockResult(null);
    if (msg.docking_status !== undefined) {
      resolved.docking_status = msg.docking_status;
    }
    else {
      resolved.docking_status = []
    }

    return resolved;
    }
};

module.exports = DockResult;
