// Auto-generated. Do not edit!

// (in-package actions_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.isdocked = null;
    }
    else {
      if (initObj.hasOwnProperty('isdocked')) {
        this.isdocked = initObj.isdocked
      }
      else {
        this.isdocked = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockGoal
    // Serialize message field [isdocked]
    bufferOffset = _serializer.int32(obj.isdocked, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockGoal
    let len;
    let data = new DockGoal(null);
    // Deserialize message field [isdocked]
    data.isdocked = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actions_tutorial/DockGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b2a74e0e3231023d3b4fd74b241fc57d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    int32 isdocked
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockGoal(null);
    if (msg.isdocked !== undefined) {
      resolved.isdocked = msg.isdocked;
    }
    else {
      resolved.isdocked = 0
    }

    return resolved;
    }
};

module.exports = DockGoal;
