// Auto-generated. Do not edit!

// (in-package actions_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class dockFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.last_dish_washed = null;
    }
    else {
      if (initObj.hasOwnProperty('last_dish_washed')) {
        this.last_dish_washed = initObj.last_dish_washed
      }
      else {
        this.last_dish_washed = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type dockFeedback
    // Serialize message field [last_dish_washed]
    bufferOffset = _serializer.string(obj.last_dish_washed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type dockFeedback
    let len;
    let data = new dockFeedback(null);
    // Deserialize message field [last_dish_washed]
    data.last_dish_washed = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.last_dish_washed.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actions_tutorial/dockFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cff4a52ffc57c5353f3b2128c70feaa7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    string last_dish_washed
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new dockFeedback(null);
    if (msg.last_dish_washed !== undefined) {
      resolved.last_dish_washed = msg.last_dish_washed;
    }
    else {
      resolved.last_dish_washed = ''
    }

    return resolved;
    }
};

module.exports = dockFeedback;
