; Auto-generated. Do not edit!


(cl:in-package om_aiv_navigation-msg)


;//! \htmlinclude ActionGoal.msg.html

(cl:defclass <ActionGoal> (roslisp-msg-protocol:ros-message)
  ((goal_goal
    :reader goal_goal
    :initarg :goal_goal
    :type cl:string
    :initform ""))
)

(cl:defclass ActionGoal (<ActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name om_aiv_navigation-msg:<ActionGoal> is deprecated: use om_aiv_navigation-msg:ActionGoal instead.")))

(cl:ensure-generic-function 'goal_goal-val :lambda-list '(m))
(cl:defmethod goal_goal-val ((m <ActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader om_aiv_navigation-msg:goal_goal-val is deprecated.  Use om_aiv_navigation-msg:goal_goal instead.")
  (goal_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionGoal>) ostream)
  "Serializes a message object of type '<ActionGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_goal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionGoal>) istream)
  "Deserializes a message object of type '<ActionGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_goal) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_goal) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionGoal>)))
  "Returns string type for a message object of type '<ActionGoal>"
  "om_aiv_navigation/ActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionGoal)))
  "Returns string type for a message object of type 'ActionGoal"
  "om_aiv_navigation/ActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionGoal>)))
  "Returns md5sum for a message object of type '<ActionGoal>"
  "db36ba6c2d7075135f6f5a5977ce9d12")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionGoal)))
  "Returns md5sum for a message object of type 'ActionGoal"
  "db36ba6c2d7075135f6f5a5977ce9d12")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionGoal>)))
  "Returns full string definition for message of type '<ActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionGoal)))
  "Returns full string definition for message of type 'ActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionGoal
    (cl:cons ':goal_goal (goal_goal msg))
))
