; Auto-generated. Do not edit!


(cl:in-package om_aiv_navigation-msg)


;//! \htmlinclude PatrolGoal.msg.html

(cl:defclass <PatrolGoal> (roslisp-msg-protocol:ros-message)
  ((goal_patrol
    :reader goal_patrol
    :initarg :goal_patrol
    :type cl:string
    :initform ""))
)

(cl:defclass PatrolGoal (<PatrolGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name om_aiv_navigation-msg:<PatrolGoal> is deprecated: use om_aiv_navigation-msg:PatrolGoal instead.")))

(cl:ensure-generic-function 'goal_patrol-val :lambda-list '(m))
(cl:defmethod goal_patrol-val ((m <PatrolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader om_aiv_navigation-msg:goal_patrol-val is deprecated.  Use om_aiv_navigation-msg:goal_patrol instead.")
  (goal_patrol m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolGoal>) ostream)
  "Serializes a message object of type '<PatrolGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_patrol))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_patrol))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolGoal>) istream)
  "Deserializes a message object of type '<PatrolGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_patrol) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_patrol) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolGoal>)))
  "Returns string type for a message object of type '<PatrolGoal>"
  "om_aiv_navigation/PatrolGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolGoal)))
  "Returns string type for a message object of type 'PatrolGoal"
  "om_aiv_navigation/PatrolGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolGoal>)))
  "Returns md5sum for a message object of type '<PatrolGoal>"
  "bbc29a4d7d524ef00ce6e69ba1c4a816")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolGoal)))
  "Returns md5sum for a message object of type 'PatrolGoal"
  "bbc29a4d7d524ef00ce6e69ba1c4a816")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolGoal>)))
  "Returns full string definition for message of type '<PatrolGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_patrol~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolGoal)))
  "Returns full string definition for message of type 'PatrolGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_patrol~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_patrol))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolGoal
    (cl:cons ':goal_patrol (goal_patrol msg))
))
