; Auto-generated. Do not edit!


(cl:in-package om_aiv_navigation-msg)


;//! \htmlinclude PlayGoal.msg.html

(cl:defclass <PlayGoal> (roslisp-msg-protocol:ros-message)
  ((goal_play
    :reader goal_play
    :initarg :goal_play
    :type cl:string
    :initform ""))
)

(cl:defclass PlayGoal (<PlayGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name om_aiv_navigation-msg:<PlayGoal> is deprecated: use om_aiv_navigation-msg:PlayGoal instead.")))

(cl:ensure-generic-function 'goal_play-val :lambda-list '(m))
(cl:defmethod goal_play-val ((m <PlayGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader om_aiv_navigation-msg:goal_play-val is deprecated.  Use om_aiv_navigation-msg:goal_play instead.")
  (goal_play m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayGoal>) ostream)
  "Serializes a message object of type '<PlayGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_play))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_play))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayGoal>) istream)
  "Deserializes a message object of type '<PlayGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_play) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_play) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayGoal>)))
  "Returns string type for a message object of type '<PlayGoal>"
  "om_aiv_navigation/PlayGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayGoal)))
  "Returns string type for a message object of type 'PlayGoal"
  "om_aiv_navigation/PlayGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayGoal>)))
  "Returns md5sum for a message object of type '<PlayGoal>"
  "499eb89c22bb904f93ef078004bb910b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayGoal)))
  "Returns md5sum for a message object of type 'PlayGoal"
  "499eb89c22bb904f93ef078004bb910b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayGoal>)))
  "Returns full string definition for message of type '<PlayGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_play~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayGoal)))
  "Returns full string definition for message of type 'PlayGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_play~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_play))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayGoal
    (cl:cons ':goal_play (goal_play msg))
))
