; Auto-generated. Do not edit!


(cl:in-package om_aiv_navigation-msg)


;//! \htmlinclude UndockGoal.msg.html

(cl:defclass <UndockGoal> (roslisp-msg-protocol:ros-message)
  ((goal_undock
    :reader goal_undock
    :initarg :goal_undock
    :type cl:string
    :initform ""))
)

(cl:defclass UndockGoal (<UndockGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <UndockGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'UndockGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name om_aiv_navigation-msg:<UndockGoal> is deprecated: use om_aiv_navigation-msg:UndockGoal instead.")))

(cl:ensure-generic-function 'goal_undock-val :lambda-list '(m))
(cl:defmethod goal_undock-val ((m <UndockGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader om_aiv_navigation-msg:goal_undock-val is deprecated.  Use om_aiv_navigation-msg:goal_undock instead.")
  (goal_undock m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <UndockGoal>) ostream)
  "Serializes a message object of type '<UndockGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_undock))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_undock))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <UndockGoal>) istream)
  "Deserializes a message object of type '<UndockGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_undock) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_undock) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<UndockGoal>)))
  "Returns string type for a message object of type '<UndockGoal>"
  "om_aiv_navigation/UndockGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'UndockGoal)))
  "Returns string type for a message object of type 'UndockGoal"
  "om_aiv_navigation/UndockGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<UndockGoal>)))
  "Returns md5sum for a message object of type '<UndockGoal>"
  "76e2244eb27616fdd29e27ef831a7cf0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'UndockGoal)))
  "Returns md5sum for a message object of type 'UndockGoal"
  "76e2244eb27616fdd29e27ef831a7cf0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<UndockGoal>)))
  "Returns full string definition for message of type '<UndockGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_undock~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'UndockGoal)))
  "Returns full string definition for message of type 'UndockGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string goal_undock~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <UndockGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_undock))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <UndockGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'UndockGoal
    (cl:cons ':goal_undock (goal_undock msg))
))
