// Auto-generated. Do not edit!

// (in-package om_aiv_navigation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class QueueDropoffGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_queueDropoff = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_queueDropoff')) {
        this.goal_queueDropoff = initObj.goal_queueDropoff
      }
      else {
        this.goal_queueDropoff = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type QueueDropoffGoal
    // Serialize message field [goal_queueDropoff]
    bufferOffset = _serializer.string(obj.goal_queueDropoff, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type QueueDropoffGoal
    let len;
    let data = new QueueDropoffGoal(null);
    // Deserialize message field [goal_queueDropoff]
    data.goal_queueDropoff = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.goal_queueDropoff.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'om_aiv_navigation/QueueDropoffGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ba4a241c8636596603c5fc2db568cb7a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string goal_queueDropoff
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new QueueDropoffGoal(null);
    if (msg.goal_queueDropoff !== undefined) {
      resolved.goal_queueDropoff = msg.goal_queueDropoff;
    }
    else {
      resolved.goal_queueDropoff = ''
    }

    return resolved;
    }
};

module.exports = QueueDropoffGoal;
